/*! Bespoke.js v0.2.1 © 2013 Mark Dalgleish, Licensed MIT */
(function(e,t,n){var r=function(e,t){var r=n.querySelector(e),s=[].slice.call(r.children,0),c=s[0],h={},p=function(e,t){if(!s[e])return;a(h,"deactivate",b(c,t)),c=s[e],s.map(v),a(h,"activate",b(c,t)),f(c,"active"),l(c,"inactive")},v=function(e,t){var n=t-s.indexOf(c),r=n>0?"after":"before";["before(-\\d+)?","after(-\\d+)?","active","inactive"].map(l.bind(null,e)),e!==c&&["inactive",r,r+"-"+Math.abs(n)].map(f.bind(null,e))},m=function(e,t){a(h,"slide",b(s[e],t))&&p(e,t)},g=function(e){var t=s.indexOf(c)+1;a(h,"next",b(c,e))&&p(t,e)},y=function(e){var t=s.indexOf(c)-1;a(h,"prev",b(c,e))&&p(t,e)},b=function(e,t){return t=t||{},t.index=s.indexOf(e),t.slide=e,t},w={on:o.bind(null,h),off:u.bind(null,h),fire:a.bind(null,h),slide:m,next:g,prev:y,parent:r,slides:s};return f(r,"parent"),s.map(function(e){f(e,"slide")}),Object.keys(t||{}).map(function(e){var n=t[e];n&&d[e](w,n===!0?{}:n)}),p(0),i.push(w),w},i=[],s={},o=function(e,t,n){(e[t]||(e[t]=[])).push(n)},u=function(e,t,n){e[t]=(e[t]||[]).filter(function(e){return e!==n})},a=function(e,t,n){return(e[t]||[]).concat(e!==s&&s[t]||[]).reduce(function(e,t){return e&&t(n)!==!1},!0)},f=function(t,n){t.classList.add(e+"-"+n)},l=function(t,n){t.className=t.className.replace(new RegExp(e+"-"+n+"(\\s|$)","g")," ").replace(/^\s+|\s+$/g,"")},c=function(e){return function(t){i.map(function(n){n[e].call(null,t)})}},h=function(e){return{from:function(t,n){return(n=n||{})[e]=!0,r(t,n)}}},p=function(e){return function(t){var r,i;n.addEventListener("keydown",function(n){var r=n.which;e==="X"?(r===37&&t.prev(),(r===32||r===39)&&t.next()):(r===38&&t.prev(),(r===32||r===40)&&t.next())}),t.parent.addEventListener("touchstart",function(t){t.touches.length&&(r=t.touches[0]["page"+e],i=0)}),t.parent.addEventListener("touchmove",function(t){t.touches.length&&(t.preventDefault(),i=t.touches[0]["page"+e]-r)}),t.parent.addEventListener("touchend",function(){Math.abs(i)>50&&(i>0?t.prev():t.next())})}},d={horizontal:p("X"),vertical:p("Y")};t[e]={from:r,slide:c("slide"),next:c("next"),prev:c("prev"),horizontal:h("horizontal"),vertical:h("vertical"),on:o.bind(null,s),off:u.bind(null,s),plugins:d}})("bespoke",this,document);

/*! bespoke-hash v0.1.1 © 2013 Mark Dalgleish, Licensed MIT */
(function(e){e.plugins.hash=function(e){var t,n=function(){var t=window.location.hash.slice(1),n=parseInt(t,10);t&&(n?r(n-1):e.slides.forEach(function(e,n){e.getAttribute("data-bespoke-hash")===t&&r(n)}))},r=function(n){n!==t&&e.slide(n)};setTimeout(function(){n(),e.on("activate",function(e){var n=e.slide.getAttribute("data-bespoke-hash");window.location.hash=n||e.index+1,t=e.index}),window.addEventListener("hashchange",n)},0)}})(bespoke);

/*! bespoke-state v0.2.1 © 2013 Mark Dalgleish, Licensed MIT */
(function(e){e.plugins.state=function(e){var t=function(t,n){var r=n.slide.getAttribute("data-bespoke-state");r&&r.split(" ").forEach(function(n){n&&e.parent.classList[t](n)})};e.on("activate",t.bind(null,"add")),e.on("deactivate",t.bind(null,"remove"))}})(bespoke);

/*! bespoke-bullets v0.1.0 © 2013 Mark Dalgleish, Licensed MIT */
(function(e){e.plugins.bullets=function(e){var t,n,r=e.slides.map(function(e){return[].slice.call(e.querySelectorAll("[data-bespoke-bullet]"),0)}),i=function(){var e=t+1;if(u(1))return o(t,n+1),!1;r[e]&&o(e,0)},s=function(){var e=t-1;if(u(-1))return o(t,n-1),!1;r[e]&&o(e,r[e].length-1)},o=function(e,i){t=e,n=i,r.forEach(function(t,n){t.forEach(function(t,r){t.classList.add("bespoke-bullet"),n<e||n===e&&r<=i?(t.classList.add("bespoke-bullet-active"),t.classList.remove("bespoke-bullet-inactive")):(t.classList.add("bespoke-bullet-inactive"),t.classList.remove("bespoke-bullet-active"))})})},u=function(e){return r[t][n+e]!==undefined};e.on("next",i),e.on("prev",s),e.on("slide",function(e){o(e.index,0)}),o(0,0)}})(bespoke);